#!/bin/sh
# shellcheck disable=SC1091
# video-link.cgi - streams one recorded clip given a valid token, with NO
# session login required. This is intentional: it's the link an email
# notification sends, meant to be opened straight from a phone's mail app.
#
# The token IS the authorization here (not a session cookie) - generated by
# petcam-video-link, one random 128-bit token per clip, looked up in
# /etc/petcam-video-tokens (space-separated "token relpath" lines, newest
# 200 kept). A token grants access to exactly the one clip it was minted
# for; guessing one is a 2^128 search. Path traversal/symlink hardening
# mirrors json-recordings.cgi (same clip storage, same risk).

TOKEN_FILE=/etc/petcam-video-tokens
STORAGE_PATH=$(raptorctl config get recording storage_path 2>/dev/null | tr -d '\r\n"')
[ -n "$STORAGE_PATH" ] || STORAGE_PATH=/mnt/mmcblk0p1/raptor
BASE="$STORAGE_PATH/clips"
REAL_BASE=$(readlink -f "$BASE" 2>/dev/null) || REAL_BASE=$BASE

qval() { printf '%s' "$QUERY_STRING" | sed -n "s/.*$1=\([^&]*\).*/\1/p"; }

TOKEN=$(qval token)

case "$TOKEN" in
	'' | *[!0-9a-f]*)
		printf 'Status: 404 Not Found\r\n\r\n'
		exit 0
		;;
esac

[ -f "$TOKEN_FILE" ] || { printf 'Status: 404 Not Found\r\n\r\n'; exit 0; }

REL=$(awk -v t="$TOKEN" '$1 == t { $1 = ""; sub(/^ /, ""); print; exit }' "$TOKEN_FILE")

safe() { case "$1" in "" | /* | *..*) return 1 ;; *) return 0 ;; esac }
within_base() {
	resolved=$(readlink -f "$1" 2>/dev/null) || return 1
	case "$resolved" in
		"$REAL_BASE"/*) return 0 ;;
		*) return 1 ;;
	esac
}

if ! safe "$REL" || [ ! -f "$BASE/$REL" ] || [ -L "$BASE/$REL" ] || ! within_base "$BASE/$REL"; then
	printf 'Status: 404 Not Found\r\n\r\n'
	exit 0
fi

F="$BASE/$REL"
SZ=$(stat -c%s "$F" 2>/dev/null || echo 0)
printf 'Status: 200 OK\r\n'
printf 'Content-Type: video/mp4\r\n'
printf 'Content-Length: %s\r\n' "$SZ"
printf 'Content-Disposition: inline; filename="%s"\r\n' "$(basename "$F")"
printf 'Connection: close\r\n\r\n'
cat "$F"
